runtime: python312
instance_class: F2

env_variables:
  APPENGINE_URL: https://etchedn.uc.r.appspot.com

beta_settings:
  cloud_sql_instances: etchedn:us-central1:etchedn-web-app-01


entrypoint: gunicorn -b :$PORT etchedn_project.wsgi:application

handlers:
- url: /static
  static_dir: app/static/
- url: /.*
  script: auto